# @package _group_

# We keep this config as an example of the environment setup on one of our machines
# It is easy to configure different machine's environemts via such configs
python_bin: anaconda3/envs/sgva/bin/python3.9
project_path: ${hydra:runtime.cwd}
before_train_commands:
  - module load cuda
  - module load gcc/10.2.0
  - conda init bash
  - source $HOME/.bashrc
  - conda activate sgva
